[workspace]
resolver = "3"
members = [
    "plitki-core",
    "plitki-map-qua",
    "plitki-audio",
    "plitki-ui-wayland",
    "plitki-gtk",
    "plitki-gnome",
    "plitki-term",
    "tools",
]

[profile.release]
overflow-checks = true
